# -*- coding: utf-8 -*-
"""twitter sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxzOXLl2PpdOi6-gnLz1MBdzxTT5_cE9
"""

#installing kaggle library
! pip install kaggle

"""UPLOADING KAGGLE.JSON FILE"""

#configuring the path of the kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json  ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#pasting kaggle api for twitter dataset to fetch the dataset from kaggle
!kaggle datasets download -d kazanova/sentiment140

# it is the zip file so extracting the data set
from zipfile import ZipFile
dataset='/content/sentiment140.zip'

with ZipFile(dataset, 'r') as zip:
   zip.extractall()
   print('The data is extracted ')

"""#importing all the packages"""

import pandas as pd
import numpy as np
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""###what is stop words
stop words doesnt give any meaning to the machine learning model , machine learnin model doesnt understand this words so we are going to remove the words


"""

#printing the stopwords
print(stopwords.words('english'))

"""#Datapreprocessing"""

#loading the data from CSV file to pandas dataframe
twitter_data=pd.read_csv('/content/twitter_compressed.csv',encoding='ISO-8859-1')

twitter_data.head()

#naming the column and reading the dataset again
column_names=['target','id','date','flag','user','text']
twitter_data=pd.read_csv('/content/twitter_compressed.csv',names=column_names,encoding='ISO-8859-1')

twitter_data.head()

# counting the number of missing values
twitter_data.isnull().sum()

"""#converting the target column "4" to "1"
"""

twitter_data.replace({'target':{4:1}},inplace=True)

#checking the distribution of the target column
twitter_data['target'].value_counts()

"""0--->Neagtive tweet
1--->positive tweet

#stemming
stemming is a process of reducing the word to its root word


eg:actor,actress,acting---act
"""

port_stem=PorterStemmer()

def stemming(content):
  stemmed_content=re.sub('[^a-zA-Z]',' ',content)
  stemmed_content=stemmed_content.lower()
  stemmed_content=stemmed_content.split()
  stemmed_content=[port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content=' '.join(stemmed_content)

  return stemmed_content

twitter_data['stemmed_content']=twitter_data['text'].apply(stemming)

twitter_data.head()

print(twitter_data['stemmed_content'])

print(twitter_data['target'])

# seperating the data and label
x=twitter_data['stemmed_content'].values
y=twitter_data['target'].values

print(x)

print(y)

"""splitting the dataset to training and testing"""

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.10,stratify=y,random_state=2)

print(x.shape,x_train.shape,x_test.shape)

print(x_train)

print(x_test)

#converting the text data into numeric
vectorizer=TfidfVectorizer()
x_train=vectorizer.fit_transform(x_train)
x_test=vectorizer.transform(x_test)

print(x_train)

print(x_test)

"""USING THE MACHINE LEARNING MODEL

LOGISTIC REGRESSION
"""

model=LogisticRegression(max_iter=1000)

model.fit(x_train,y_train)

"""#MODEL EVALUATION"""

#accuracy score on the training data
x_train_prediction=model.predict(x_train)
training_data_accuracy=accuracy_score(y_train,x_train_prediction)

print('Accuracy score on the training data:',training_data_accuracy)

# so now we have shown only the training data to the model , now we have to check the testin accuracy

#accuracy score for the testing data
x_test_prediction=model.predict(x_test)
testing_data_accuracy=accuracy_score(y_test,x_test_prediction)

print('Accuracy score for the testing data:',testing_data_accuracy)

"""MODEL ACCURACY="""

import pickle

name="trained_model.pkl"
pickle.dump(model,open(name,'wb'))

"""##using the saved model for future predictions"""

#loading the saved model

loaded_model=pickle.load(open("/content/trained_model.pkl",'rb'))

x_new=x_test[100]
print(y_test[100])

prediction=loaded_model.predict(x_new)
print(prediction)

if (prediction[0]==0):
  print("negative tweet")

else:
  print("positive tweet")